name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ python3-dev libtbb-dev

      # Configure the project
      - name: Configure CMake
        run: |
          cmake -S . -B build -DPYTHON_EXECUTABLE=$(which python3)
          cmake --build build

      # Run tests
      - name: Run tests with CTest
        run: |
          cd build
          ctest --output-on-failure

