name: Windows Visual Studio Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  msvc2022:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set BOOST_ROOT environment variable
        run: echo "BOOST_ROOT=C:\\local\\boost_1_81_0" >> $env:GITHUB_ENV
        shell: powershell

      - name: Run CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022"

      - name: Build
        run: cmake --build build --config Release --parallel 10

      - name: Test
        run: |
          cd build
          ctest -C Release -j 10 --output-on-failure
        shell: cmd
