name: CMake Build and Test on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022  # Use the latest Windows environment with Visual Studio 2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          choco install cmake --install-arguments="'/S' /l=3" --version=3.27.0
          choco install ninja
          choco install python --version=3.12.0
          refreshenv  # Refresh environment variables to use the newly installed tools

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Ninja" -DPYTHON_EXECUTABLE=C:/Python312/python.exe
          cmake --build build

      - name: Run tests with CTest
        run: |
          cd build
          ctest --output-on-failure
